### ISSUE TITLE
Regression with Euro symbol in String management.

### ISSUE THREAD

**Issue by VincentSalewyn** [ibmruntimes/openj9-openjdk-jdk22#60]
SPSS Text Analytics upgraded JRE from IBM Semeru 11.0.13 to 11.0.22 and we have a regression in a piece of our code that I don't understand.

I made some further tests and it appears the regression appears in 11.0.21 (no problem with 11.0.20.1).

The problem can be easily reproduced (see code below).
As summary:
- Create a first String valueSymbol as "€:euros"
- Split the string  on ":" character to get an array lSymbols of 2 elements : "€" and "euros"
-  Create a second String input  as "25 euros"
- Check if the input String contains the second element of lSymbols array using indexOf method. This method should always return 3. With JRE 11.0.21, it returns -1.

Note that if you change the "€" symbol by "$" symbol in the symbolValue string, you get correct results.

```
public class MyTest {

	 public static void main( String[] args )
	    {
		 	String symbolValue = "€:euros";
		 	// String symbolValue = new String("$:euros");
		 	String[] lSymbols = symbolValue.split(":");
		 	String value = lSymbols[1];
		 	String input = "25 euros";
		 	int pos = input.indexOf(value);	 	

                        System.out.print("String: \"" + value);
		 	System.out.print(pos != -1 ? "\" found in \"" : "\" not found in \"");
		 	System.out.print(input + "\"");
	        
	    }
}
```
Execution in 11.0.22 gives : 

`String: "euros" not found in "25 euros"
`

Am I doing something wrong ? Should I add a VM argument to make it work ?

**Comment by pshipton** [comment]
It's a bug with https://eclipse.dev/openj9/docs/version0.41/#-xxcompactstrings-option-enabled-by-default. You can run with `-XX:-CompactStrings` until we fix it in the next release.

**Comment by VincentSalewyn** [comment]
@pshipton Thanks for your quick answer. I noticed the place to create issues.

**Comment by pshipton** [comment]
Another workaround is to move to jdk17, which doesn't have the same problem, although compact strings are also enabled by default there.

**Comment by pshipton** [comment]
Closing since https://github.com/eclipse-openj9/openj9/pull/19607 is merged.
